In [1]:
import numpy as np
import pandas as pd

In [2]:
# version of numpy installed
np.__version__

'1.21.5'

In [3]:
# read dataset
data = pd.read_csv('data.csv')

In [5]:
# Number of records in the dataset
data.shape

(11914, 16)

In [6]:
data.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

In [38]:
# The most popular car manufacturers
data['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [21]:
df = data[data['Make'] == 'Audi']

In [34]:
# Number of unique Audi car models
df['Model'].nunique()

34

In [51]:
# Number of columns with missing values
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [44]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [61]:
# Find the median value of "Engine Cylinders" column in the dataset.
data['Engine Cylinders'].median()

6.0

In [71]:
# calculate the most frequent value of the same "Engine Cylinders
data['Market Category'].value_counts().head(3)

Crossover    1110
Flex Fuel     872
Luxury        855
Name: Market Category, dtype: int64

In [72]:
# fillna method to fill the missing values with the most frequent value
data['Engine Cylinders'] = data['Engine Cylinders'].fillna(4)
data['Engine HP'] = data['Engine HP'].fillna(200.0)
data['Engine Fuel Type'] = data['Engine Fuel Type'].fillna('regular unleaded')
data['Number of Doors'] = data['Number of Doors'].fillna(4.0)
data['Market Category'] = data['Market Category'].fillna('Crossover')

In [64]:
# calculate the median value of "Engine Cylinders" once again
data['Engine Cylinders'].median()

6.0

In [73]:
data.isnull().sum()

Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [78]:
# Select all the "Lotus" cars from the dataset
df = data[data['Make'] == 'Lotus'] 

In [81]:
# Select only columns "Engine HP", "Engine Cylinders"
df = df[['Engine HP', 'Engine Cylinders']]
df.head(3)

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0

In [85]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows)
df = df.drop_duplicates()
df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [87]:
# Get the underlying NumPy array. Let's call it X.
X = df.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [101]:
# Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
x = X.T
XTX = x.dot(X)

In [102]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [109]:
# Invert XTX.
XTX = np.linalg.inv(XTX)

In [110]:
XTX 

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [117]:
# Multiply the inverse of XTX with the transpose of X
z = XTX.dot(x)
z

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [119]:
#  multiply the result by y. Call the result w.
w = z.dot(y)

#What's the value of the first element of w?
w

array([  4.59494481, -63.56432501])